sudo: required
dist: focal
language: c

cache:
    apt: true

before_install:
  - sudo apt-get update -q -y
  - sudo apt-get install git libc6-dev-i386 libboost-all-dev gcc-multilib gcc g++ python make automake m4 libtool -y -f

before_script:
  - git submodule update --init
  - git submodule foreach git pull origin master

script:
  - ls
