#!/bin/bash

[[ ! $(which vlc) ]] && echo "need vlc" && exit 1
if [ -f "$1" ]; then
    fyle=`realpath "$1"`
fi

get_vlc_addr()
{
    addr=`ss -ltp | grep "\"vlc\"" | awk '{print $4}'`
    vlcaddr="${addr/:/ }"
}

if [ "$fyle" != "" ]; then
    killall vlc 2>/dev/null && sleep 0.1
    vlc --intf dummy  -I rc --rc-host 0.0.0.0:0 2>/dev/null && sleep 0.1
fi
get_vlc_addr
if [ "$fyle" != "" ]; then
    echo "add $fyle" | nc -w 0 $vlcaddr
else
    [[ "$vlcaddr" == "" ]] && vlc --intf dummy  -I rc --rc-host 0.0.0.0:0 2>/dev/null
    sleep 0.1
    get_vlc_addr
    echo "$1" | nc -w 1 $vlcaddr
fi
